name: Xbox One / Series

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Build
      shell: cmd
      run: |
        cd ${{ github.workspace }}\Packaging\xbox-one
        build.bat

    - name: Copy artifacts to package directory
      run: >
        New-Item -Path build\uwp-project -Name pkg -ItemType Directory -Force &&
        Get-Childitem -Path build\uwp-project\AppxPackages, build\uwp-project\Release
        -Include Microsoft.VCLibs.x64.*.appx, devilutionX_*_x64.appx -File -Recurse |
        Copy-Item -Destination build\uwp-project\pkg\

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v3
      with:
        name: devilutionx-xbox-one
        if-no-files-found: error
        path: |
          build/uwp-project/pkg/
